### ISSUE TITLE
demontrator/app.py empty model loader drop-down list for image pairs data loader

### ISSUE THREAD

**Issue by elmokhtar-mohamedmoussa-idnow** [mammoth-eu/mammoth-commons#23]
Hello,

I am trying to run a fairbench pipeline with Image pairs (its working on the csv example).

I filled this screen with the same parameters from : https://github.com/mammoth-eu/mammoth-commons/blob/dev/tests/_test_tc6_facex_fv.py

![Screenshot from 2024-10-22 14-59-49](https://github.com/user-attachments/assets/ef914325-81d0-45e8-9c88-0239af7f6b66)

the next screen for model loader doesn't show any choices for model loader to chose from :

![image](https://github.com/user-attachments/assets/cb5e4322-6d91-4e05-88a5-3b3ce636eea2)

Best,
Elmokhtar.

**Comment by maniospas** [comment]
Hi and thanks for reporting!
This is a duplicate #19 , so I am closing this and let us continue the discussion there.
If either you or @gsarridis test the change I recommend there and it works, please either report that it works so that I add it in the main codebase, or -preferably- create a pull request with it.

**Comment by maniospas** [comment]
Reopening this because this should have been fixed in pull request #24 . Can you verify that it is working on your end  @elmokhtar-mohamedmoussa-idnow ? If it does, please close this again.

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
Hi Manios,
Thank you for the fix ! 
![image](https://github.com/user-attachments/assets/4e0a1dd5-4560-4742-bde5-702c7e9d7073)
I can run faceX now directly in the demonstrator. EDIT: the multiple plot popup issue is back
But in step 3 I only have this option I can't choose fairbench for example. (i can open another issue)

**Comment by maniospas** [comment]
For the time being, I added forceful throttling of matplotlib (similarly to the tests - the issue still persists under the hood but this requires investigation on dependency behavior that is different in different platforms and may). Please pull and check if the popus are fixed. Close this issue if this module works.

Please also open a separate issue for not being able to select fairbench.
Because that is both intentional and the fault of needing to remain compatible with the main toolkit; the latter does not support currently datatype inheritance (in this case to let the same module process both ONXX and Torch data) and we need to have a full discussion on how to address this issue - I have made preparations for several options, but we need to select one.

**Comment by maniospas** [comment]
This fix is pushed alongside commit [28b9eb7](https://github.com/mammoth-eu/mammoth-commons/commit/28b9eb765072eb2d6165a1ba62f89562d7236778) (I accidentally pushed after the above reply). 

I also added some descriptions from the facex paper too. Open a separate issue if more details are needed.

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
pop-up issue fixed ! 
I will open a separate issue for fairbench.
Thank you a lot Manios !
